// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Event struct {
	Contract string   `json:"contract"`
	Topics   []string `json:"topics"`
}

type JobConfirmation struct {
	ID    string `json:"id"`
	Event *Event `json:"event"`
}

type NewEvent struct {
	StartBlock string   `json:"startBlock"`
	Contract   string   `json:"contract"`
	Topics     []string `json:"topics"`
}

type Task struct {
	ID          string `json:"id"`
	StartBlock  string `json:"startBlock"`
	Event       *Event `json:"event"`
	SubmittedAt string `json:"submittedAt"`
}
